-- MySQL Script generated by MySQL Workbench
-- Tue Nov  4 15:55:25 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pubrelease
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pubrelease` ;
CREATE SCHEMA IF NOT EXISTS `pubrelease` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `pubrelease` ;

-- -----------------------------------------------------
-- Table `pubrelease`.`pub_project_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubrelease`.`pub_project_type` ;

CREATE TABLE IF NOT EXISTS `pubrelease`.`pub_project_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `typename` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `description` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `isuse` TINYINT NULL DEFAULT 1,
  `rowindex` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubrelease`.`pub_publish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pubrelease`.`pub_publish` ;

CREATE TABLE IF NOT EXISTS `pubrelease`.`pub_publish` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `projectid` INT NOT NULL,
  `filename` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `publishdate` DATETIME NULL,
  `updates` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT '这个家伙很懒,没有写更新内容' COMMENT '更新内容',
  `isuse` TINYINT NULL DEFAULT 1,
  `memo` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pub_public_release_pub_project_type_idx` (`projectid` ASC),
  CONSTRAINT `fk_pub_public_release_pub_project_type`
    FOREIGN KEY (`projectid`)
    REFERENCES `pubrelease`.`pub_project_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
